### PR TITLE
Remove libgsl0ldbl from several Dockerfiles. Fix build documentation,…

### PR DESCRIPTION
**Pull request by sneumann**
Remove libgsl0ldbl from several Dockerfiles, except flow,
which looks a bit different than e.g. proteomics. 

extend and fix build documentation.

### CODE REVIEW

**Comment by dtenenba** [comment]
I am having an issue building release_metabolomics:

```
[dtenenba@taipan release_metabolomics (master)]$ pwd
/home/dtenenba/bioc_docker/out/release_metabolomics
[dtenenba@taipan release_metabolomics (master)]$ docker build -t bioconductor/release_metabolomics .
...
Step 6 : RUN apt-get update &&     apt-get install -y -t unstable     libcairo2-dev     libexpat1-dev     libgmp3-dev     liblapack-dev     libnetcdf-dev     libopenbabel-dev     libgl1-mesa-dev     libglu1-mesa-dev     libgsl0-dev     openjdk-8-jdk
 ---> Running in 34caa4cee8e7
Hit:1 http://security.debian.org testing/updates InRelease
Hit:2 http://mirrors.accretive-networks.net/debian sid InRelease
Hit:3 http://mirrors.accretive-networks.net/debian testing InRelease
Ign:4 http://ftp.de.debian.org/debian jessie InRelease
Hit:5 http://mirrors.accretive-networks.net/debian testing-updates InRelease
Hit:6 http://ftp.de.debian.org/debian jessie Release
Reading package lists...
/mirrors.accretive-networks.net/debian testing-updates InRelease
Hit:6 http://ftp.de.debian.org/debian jessie Release
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libexpat1-dev is already the newest version (2.2.0-1).
libexpat1-dev set to manually installed.
liblapack-dev is already the newest version (3.6.1-2).
liblapack-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgsl0-dev : Depends: libgsl0ldbl (= 1.16+dfsg-2) but 1.16+dfsg-4 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update &&     apt-get install -y -t unstable     libcairo2-dev     libexpat1-dev     libgmp3-dev     liblapack-dev     libnetcdf-dev     libopenbabel-dev     libgl1-mesa-dev     libglu1-mesa-dev     libgsl0-dev     openjdk-8-jdk' returned a non-zero code: 100
```

**Comment by sneumann** [comment]
Hi, thanks for the note, I am on it as we speak. Some Debian package confusion.

**Comment by sneumann** [comment]
The issue seems to be that the `apt-get install -t unstable libgsl0-dev` pulls in 
`libgsl0-dev (1.16+dfsg-2)` from Jessie (https://packages.debian.org/jessie/libgsl0-dev)
and it tries to satisfy the dependency with 
the wrong `libgsl0ldbl (1.16+dfsg-4)` from sid: https://packages.debian.org/sid/libgsl0ldbl

Did you build release_base and release_core recently/today ? Could there be a mismatch 
in the apt available package lists ?

**Comment by sneumann** [comment]
In theory release_proteomics should have the same issue. Can you confirm ?

**Comment by sneumann** [comment]
Ok, here it helped to comment out 
`deb http://ftp.de.debian.org/debian jessie main` in `/etc/apt/sources.list`
then the matching versions were installed. But since I had success building everything 
afresh at https://hub.docker.com/r/sneumann/
maybe it also helps to rebuild a consistent set of release_\* images.

Yours, Steffen

**Comment by dtenenba** [comment]
You may be right [above](#issuecomment-238352417). I am rebuilding and re-pushing base and core now. Your latest changes have not been included because there were modified files that were blocking the git pull on the machine where the images are built. So now that I have the latest code I am rebuilding them. This should auto-correct tomorrow.

**Comment by dtenenba** [comment]
Even after rebuilding base and core, I still get this error. Can you send a pull request in which the line referenced [above](#issuecomment-238359988) is commented out?

**Pull request merged**
