### PR TITLE
Add Metabolomics BioC view

### PR DESCRIPTION
**Pull request by sneumann**
Known build failure for old release (BioC-3.2). 
Also adds rudimentary information to README.md 
how to build the images.

### CODE REVIEW

**Comment by dtenenba** [comment]
As it says in the install.R files, you should not edit them. Instead edit install.R.in, from which the install.R files are generated.

**Comment by sneumann** [comment]
On Do, 2016-07-28 at 15:34 +0000, Obenchain, Valerie wrote:

> As you're probably aware, many of the containers were failing to build
> due (in part) to outdated versions. Dan updated config.yml yesterday and
> we are monitoring the builds of the other containers.
> 
> Can you please merge your branch with master and update your pull
> request (i.e., no changes needed to config.yml )?

I am not entirely sure if I understood @vobencha correctly w.r.t. "no changes needed to config.yml"
but this pull request now includes the merge of upstream,
and I re-built everything here and both release/devel and core/base/metabolomics 
build fine. I haven't checked the others. Yours, Steffen

**Comment by vobencha** [comment]
What I meant re: config.yml was that the file didn't need any changes after the ones Dan made. I don't think this change is necessary
       use_numbered_branch: "false"
because use_numbered_branch is only used if use_r_devel is true. The change isn't a problem just not essential.
Thanks for the pull request.

**Comment by sneumann** [comment]
Will the devel_metabolomics appear magically on https://hub.docker.com/r/bioconductor/ ?
Or is there anything you'd have to adapt ? Could the maintainer field https://github.com/Bioconductor/bioc_docker/blob/master/src/metabolomics/Dockerfile.in#L9 be an issue ?

**Comment by vobencha** [comment]
I thought it would have just appeared; I don't think the maintainer field is the problem. I sent an email to Dan but he's out this week with sporadic email access.

I'm still figuring this out but here's what I think. Images are pushed to dockerhub by both a) an automatic build triggered by a code change in the bioc_docker github repo and b) daily builds pushed from a machine inside Fred Hutch (called taipan). I believe the taipan builds were set up so we'd have the more frequent daily builds vs just builds triggered by a code change in the github repo. I'd like to eventually simplify this - be done with taipan and have more frequent builds occur between the github repo and dockerhub.

The date of last build under 'tags' in dockerhub is >= 3days ago so images are not being pushed from taipan on a daily basis. I'm looking into this and why metabolomics didn't automatically post. I'll let you know when I have more info.

**Comment by dtenenba** [comment]
@sneumann have you tried building the image on your own computer with 

```
rake release_metabolomics
```

?

**Comment by sneumann** [comment]
Hi @dtenenba , without auth.yml this fails.
Could you send me an auth.yml (with actual credentials removed, of course) so I can try ? I will then also `git add auth.yml.template' so developers know where to put their credentials,
and document it.

**Comment by dtenenba** [comment]
Try this:

```
---
username: dtenenba
password: not_my_real_password
email: dtenenba@fhcrc.org
```

This will not allow you to push but it should still allow you to try to run rake.

When I tried the rake command above it did not work, so it seems like maybe there is more work to be done.

**Comment by sneumann** [comment]
Hi, you have a new pull request https://github.com/Bioconductor/bioc_docker/pull/6
which fixes the apt-get for libgsl. It is pulled in automatically by libsgl-dev.

**Comment by sneumann** [comment]
Hi, thanks for pulling #6 . I can confirm the [devel|release]_metabolomics images work, 
see https://hub.docker.com/r/sneumann/ .

**Pull request merged**
