### PR TITLE
Add dockerhub build badges 

### PR DESCRIPTION
**Pull request by sneumann**
Add dockerhub build badges via https://github.com/niccokunzmann/dockerhub-build-status-image
This will look like: https://github.com/phnmnl/bioc_docker/tree/feature/dockerBuildBadges
Currently, badges are broken for the cytometry builds, 
this is reported as https://github.com/niccokunzmann/dockerhub-build-status-image/issues/15

Yours, Steffen

### CODE REVIEW

**Comment by sneumann** [comment]
shields.io is reporting "repo not found" for the cytometry images. 
I couldn't find my typo, leaving as it is now. Yours, Steffen

**Comment by lshep** [comment]
Until we can figure out why cytometry2 is not being found I'm not in favor of merging this over.

**Comment by sneumann** [comment]
Hi, just committed a fix: the newer repos like cytometry need t different path to the *.svg badge. 
Works now on https://github.com/Bioconductor/bioc_docker/tree/feature/dockerBuildBadges
Yours, Steffen

**Comment by sneumann** [comment]
Closing this pull, since I messed up the git rebase. Will open a new one.

**Pull request closed without merging**
