### PR TITLE
 add cytometry Container

### PR DESCRIPTION
**Pull request by mikejiang**
related to #69

### CODE REVIEW

**Comment by lshep** [comment]
It looks like in the config.yml file you updated to include the biocViews:  FlowCytometry.   Was the intent to make the docker image include all the packages with this biocView term?  If so your install script should be updated to something like the src/protmetcore/install.R.in  (proteomics and metabolomics install.R.in  files also do this) where it uses the biocViews term to filter packages.     
Your current install.R.in  file would take the base image (which only have BiocManager, Matrix, KernSmooth, mgcv)  and then only install the packages you have listed `pkgs <- c("biocViews", "CytoML", "roxygen2", "devtools")`   .  This would install the biocViews package not the packages listed under the term specified.

**Comment by mikejiang** [comment]
I actually do not intend to include all the packages under `FlowCytometry` term. Instead, we want to narrow down to the core cytometry infrastructure tools maintained by RGLab. `CytoML` sits at the top of dependency tree thus should cover all the basics users will need.

**Comment by lshep** [comment]
OK just wanted to double check.   I'll continue over merging the pull request and setting up the dockerhub for the new repository -  I'll let you know if I run into any issues.

**Comment by mikejiang** [comment]
Great, thanks a lot!

**Pull request merged**
